### ISSUE TITLE
Toast not visible if modal variant="flyout" is open

### ISSUE THREAD

**Issue by clinically-au** [livewire/flux#164]
If a modal is open with the flyout variant, toasts are not visible as they appear to be behind the flyout.

**Comment by Havenstd06** [comment]
Same problem here, but not necessarily the flyout variant. I can't get my notifications in front of the modal and backdrop, even when specifying a z-index. If anyone has a solution, I'd love to hear from you! 🙏🏻

**Comment by calebporzio** [comment]
Ok, I dug deep on this one. Here's a writeup for those who care (a partial fix will be in the next release). Thanks for this report:

Consider the following element arrangements that are capable of rendering in the top-layer:

A) `<div popover="auto">` (triggered by `.showPopover()`)
B) `<div popover="manual">`  (triggered by `.showPopover()`)
C) `<dialog>`  (triggered by `.show()`)
D) `<dialog>`  (triggered by `.showModal()`)
E) `<dialog popover="auto">`  (triggered by `.showPopover()`)
F) `<dialog popover="manual">`  (triggered by `.showPopover()`)

If two top-layer elements are visible, the one triggered LAST will show up on top.

For example:

```html
<div popover="auto" id="foo">Foo</div>
<div popover="auto" id="bar">Bar</div>

// If you run, `bar.showPopover(); foo.showPopover()`
// "Foo" will show up on top of "Bar"
```

However, there are special rules when dealing with `<dialog>` elements that are triggered by `.show()` (not `.showModal()`). Because these are triggered simply with `.show()`, let's call them "non-modal" dialogs.

Here are the exceptions to the "most recently triggered shows up on top" rule:

**Exception 1) Non-modal dialogs lose to modals and popovers**
If you are triggering both a non-modal dialog and either a modal dialog (`.showModal()`) or a manual popover (`popover="manual"`), the non-modal dialog will always lose, even if it was called last:

```html
<dialog id="foo">Foo</dialog>
<div popover="manual" id="bar">Bar</dialog>
```

**Exception 2) Two non-modal dialogs shown**
It doesn't matter which order non-modal dialogs are triggered, whichever appears last in the DOM will remain on top.

```html
<dialog id="foo">Foo</dialog>
<dialog id="bar">Bar</dialog>
```

**Exception 3) Auto popovers**
If a non-modal dialog is triggered along with a `[popover="auto"]` element using `.showPopover`, the typical rules of "whichever is triggered last" will win.

```html
<dialog id="foo">Foo</dialog>
<div popover id="bar">Bar</div>
```

---

What was happening with Flux's toast being hidden by flyout modals:
* The modal's were using `.showModal()`
* The toast was using `.show()`

Therefore, Exception 1 applied: the toast always lost and was shown BEHIND the modal dialog.

To fix this, we're now using a `<div popover="manual">` instead of a `<dialog popover="manual">`, and are using `.showPopover()` instead of `.show()`.

This fixes the display problem, however, it introduces a new problem:

The toast won't receive click events. It will be visually on top of the modal, but functionally below it.

Therefore, this PR is only a stop-gap for the time being. Hopefully this is considered a bug in browsers (both Chrome and Safari behave this way) and be fixed at some point.
