### ISSUE TITLE
<flux:modal.trigger in Header

### ISSUE THREAD

**Issue by melokullc** [livewire/flux#165]
<flux:modal.trigger when inside header, doesn't trigger flyout modal to open.

If there is a different approach to this working, please let me know.

**Comment by calebporzio** [comment]
Ah thanks for the report. This was because the `flux:modal.trigger` component was used outside a Livewire component and therefore outside an Alpine component, however it relies on Alpine to dispatch the events it needs to work properly.

Therefore, I've added `x-data` to the modal trigger which has fixed it. Will be available in the next release. Thanks.
