### ISSUE TITLE
Incompatibility with Tailwind Forms

### ISSUE THREAD

**Issue by ju5t** [livewire/flux#306]
This is a follow-up to #68 and has been already pointed out by @lucasromanojf too in #62. 

Perhaps it should be documented that the tailwindcss/forms is not compatible with Flux UI. At least not yet. And that it's advised to disable it, because chances are focus rings get mangled up. There may be other issues we're not aware of.

I've copied the image from #62 to illustrate the problem in this issue as well.

![Image](https://github.com/user-attachments/assets/41bf985d-98b2-418b-95aa-f41ebaef3eba)

**Comment by joshhanley** [comment]
@ju5t thanks for reporting! I have submitted a PR to add this note to the docs.

**Comment by calebporzio** [comment]
Merged Josh's PR to add a note for folks. Closing.

**Comment by ventrec** [comment]
I stumbled upon the same issue yesterday and managed to make it work by changing the strategy option of the forms plugin to "class".

**In tailwind.config.js:**
```js
plugins: [
  require('@tailwindcss/forms')({ strategy: 'class' }),
],
```

I only had to update my existing blade form components to use the generated `form-input`, `form-select`... classes in order to maintain the styling of those elements.

Here's an overview of all relevant classes that should be applied with this strategy: https://github.com/tailwindlabs/tailwindcss-forms?tab=readme-ov-file#using-classes-to-style
