### ISSUE TITLE
Navlist item translates a bit if current due to missing border width

### ISSUE THREAD

**Issue by dimitri-koenig** [livewire/flux#308]
Hi there

The navlist item button moves if it is current due to the border having a width only if it is current.

The solution is to set a transparent border with with and only change the color if it is current.

```diff
+++ b/vendor/livewire/flux-pro/stubs/resources/views/flux/navlist/item.blade.php
@@ -19,7 +19,7 @@
 $classes = Flux::classes()
     ->add('h-10 lg:h-8 relative flex items-center gap-3 rounded-lg')
     ->add($square ? '!px-2.5' : '')
-    ->add('py-0 text-left w-full px-3 my-px border-zinc-200')
+    ->add('py-0 text-left w-full px-3 my-px border border-transparent')
     ->add('text-zinc-500 dark:text-white/80 hover:text-zinc-800 hover:dark:text-white')
```

**Comment by joshhanley** [comment]
@dimitri-koenig thanks for reporting!

I just had a look in my browser and a non-current item has a width of 40px (and no border) and a current item has a width of 38px, with a 1px border = 40px.

So I'm not sure exactly what the issue is. Please re-submit this issue with some code and screenshots that demonstrate the issue, so we can reproduce.

Thanks!

**Comment by dimitri-koenig** [comment]
@joshhanley, thx for looking into it. Sorry I forgot to include a short capture video, that would have made things easier to understand.

![Image](https://github.com/user-attachments/assets/32bfdc99-23ed-4f45-b586-86e7293e21b5)

I tried this with a "naked" tailwind/flux installation.

**Comment by dimitri-koenig** [comment]
@joshhanley, do you mind reopening this issue?
