### ISSUE TITLE
Dropdowns and tooltips are broken on iOS 16 browsers

### ISSUE THREAD

**Issue by binaryfire** [livewire/flux#335]
Hi guys

I'm using an iPhone X with the latest iOS version that runs on it (iOS 16). The iPhone X is still supported by Apple and gets regular updates. A lot of people are still on [slightly older iphones.](https://www.reddit.com/r/iphone/comments/1drj910/how_many_of_you_are_still_using_the_legendary/)

Dropdowns and tooltips don't work on any browser on my phone. They're open as soon as the page is loaded and can't be closed. All iOS versions of browsers use Webkit (even Chrome) so it makes sense the same issue is present on all of them. Screenshots below. My apps are often used on mobile devices so this is a major issue for me. I tweeted about this a couple of times but never got a reply so figured I'd try here.

Chrome:
![Image](https://github.com/user-attachments/assets/4f324873-e48b-4426-b010-b6cadb8e2218)

Safari:
![Image](https://github.com/user-attachments/assets/dcddcf1b-ff7d-4f0e-8809-b801a7d62e85)

Safari:
![Image](https://github.com/user-attachments/assets/0b749884-53f3-46c0-aec3-bd73235ecf06)

**Comment by rhiannonjourney** [comment]
I've run into this issue also. I think its because Flux uses the native Popover attribute which is not supported in iOS 16 and below. There are some popover polyfills that exist, but they can't replicate the native behavior 100% so they probably wouldn't fix it. I have some public facing projects I'd love to use Flux on but I can't since iOS 16 support is required for them.

**Comment by binaryfire** [comment]
@rhiannonjourney Thanks for the info.

If dropdowns are using the popover API, then the problem isn’t just limited to iOS 16.

- It’s still listed as only partially supported: https://developer.mozilla.org/en-US/docs/Web/API/Popover_API

- Can I Use says there’s only 75% global support right now: https://caniuse.com/?search=popover

- There’s an open bug re: closing popups in WebKit: https://bugs.webkit.org/show_bug.cgi?id=267688


This really should have been checked. It’s essential to check any attribute that will be used in a UI library in Can I Use, and anything less than ~95% should be avoided. Or a polyfill needs to be added. Also shouldn’t there have been some browser testing?

If I sound frustrated, it’s because I am. I pinged Caleb several times on Twitter but there was never any follow up. If you’re building serious apps you need to be able to rely on the devs of the UI libraries you’re using to make sure things work on desktop, mobile and all the major browsers.

**Comment by calebporzio** [comment]
It's actually more like 85% because the "partial support" at least allows them to be toggled like normal (just doesn't support "click outside" - which we've removed the native one anyways and rolled our own so this will work).

![Image](https://github.com/user-attachments/assets/82fda938-a589-47f0-be33-9e8d5af353ef)

I understand this is still a new technology and not as ubiquitous as `<dialog>` is. However, we've made the decision to use `popover` and aside from maybe adding a polyfil, we don't have plans to move away from it.

I do agree we can do a better job with messaging however, to make users aware `[popover]` isn't over 90% supported in browsers.
