### ISSUE TITLE
Larger clickable area on radio buttons

### ISSUE THREAD

**Issue by mauritskorse** [livewire/flux#34]
It feels as if radio buttons require quite precise clicking to select them.
It would be useful to increase this clickable area (padding and the gap between radio and label)
It would also be helpful if the description would be clickable as well to select the button. 

I have tried to improve it by adding a div around them that when clicked checks the radiobutton. Unfortunately that breaks the wire:model functionality.

**Comment by patrykszady** [comment]
How is the radio button "radius" in flux different than in tailwind or plain html? If it's not, then this is more of a request. Remember - Flux is Bring Your Own Spacing. You can always override any flux class as well. See docs and vids.

**Comment by calebporzio** [comment]
Yeah, in this case I'd defer to just HTML radio buttons being the same. Also I checked around the web for what is the "right" way to do descriptions, and most often descriptions don't trigger radio clicks so that you can selected their text without triggering a selection I imagine.

Nonetheless, I think the true solution is to add a new radio variant called "card" or something that makes the entire area clickable.

That's on the roadmap, so I'm going to close this. Thanks!

**Comment by mauritskorse** [comment]
Sorry for the bump.
Indeed, for consistency this would be good. 
The issue however remains that the gap between the radio button and the label in unclickable. It feels like as if this should be some 'safe area' since it is obvious that when someone clicks right in between, its intention is to select the button:
![image](https://github.com/user-attachments/assets/168b1224-2003-45a2-b8a3-568cd46515bd)

On a side note: For now I have a 'hacky' version of that card variant using `@click.self="event.target.querySelector('ui-radio')._selectable.press()"` on the wrapping element. Just curious if that would be the right way to go. Problem is that clicking the gap is still not working though.
