### ISSUE TITLE
(Input) error message does not show without label attribute in flux:input

### ISSUE THREAD

**Issue by omniith** [livewire/flux#366]
Hi team,

I am using TALL stack and found this issue that the error message does not show.

Does not show:
`<flux:input wire:model="name"/>`

Error message shows:
`<flux:input wire:model="name" label="Name" />`

the border css does change for first example. everything works fine in second example.

**Comment by jeffchown** [comment]
@omniith This looks like it is by design.  In the `resources/views/flux/with-field.blade.php` blade file (which is called via `<flux:with-field :$attributes :$name>` in the `resources/views/flux/input/index.blade.php` file), there is a conditional block of code that indicates the full error text is only shown if a `$label` or `$description` is provided:

```
<?php if ($label || $description): ?>
    <flux:field>
        <?php if ($label): ?>
            <flux:label :$badge>{{ $label }}</flux:label>
        <?php endif; ?>

        <?php if ($description): ?>
            <flux:description>{{ $description }}</flux:description>
        <?php endif; ?>

        {{ $slot }}

        <flux:error :$name />

        <?php if ($descriptionTrailing): ?>
            <flux:description>{{ $descriptionTrailing }}</flux:description>
        <?php endif; ?>
    </flux:field>
<?php else: ?>
    {{ $slot }}
<?php endif; ?>

```

I assume one reason this is done is to provide us with the ability for a minimalist error display via the css red border only in case we are displaying the input in a way that the error message would break the layout somehow.
