### ISSUE TITLE
Tooltip on mobile

### ISSUE THREAD

**Issue by ITSYV** [livewire/flux#377]
Currently, tooltips only work on desktops while hovering over the item. 
Maybe an idea to also make it available on mobile/tablets on touch/click?

**Comment by LasseRafn** [comment]
just curious, but wouldn't that make the button or action require two taps? 

Is this ideal behaviour on mobile, I've always assumed on mobile you'd display the help/tooltip text visibly instead of a tooltip. 

Maybe opt-in for this would be good, can see the benefit but also some potential annoyance for applications with lots of tooltips (eg if using icon buttons that all has a tooltip to explain the action)

**Comment by boettges** [comment]
I assume the tooltips work on tablets with pointer control (tested on iPadOS 18). 

Maybe an idea would be to add an option to append a small button-less "?" or "info (i)" icon to the button to toggle the tooltip if a mobile browser was detected. 

Alternatively, tooltips could be shown explicitly as text in the UI. For that it would be great to access the tool tip content and show it conditionally on mobile only.

**Comment by calebporzio** [comment]
Yeah, I think in general, tooltips are reserved for mouse devices.

However, I acknowledge the potential need for a generic `<flux:popover>` component to make non-navigation based popovers like mentioned here:

![Image](https://github.com/user-attachments/assets/db71d154-3514-4600-b01c-50cbd83e7ff7)
Reference: https://react-spectrum.adobe.com/react-aria/Tooltip.html
