### ISSUE TITLE
Laravel - Flux component is being executed when it is not being used.

### ISSUE THREAD

**Issue by lcallif** [livewire/flux#411]
The Views section of debugbar is showing each of the following as a view.  As I am trying to trim down all the excess db hits, views, & models, this seems to be unnecessary overhead....  

Example 1:  I am not using icons

```
10x ab18b3e58a3b1bb5106ced208a8bd460::button.indexindex.blade.php#?blade
10x ab18b3e58a3b1bb5106ced208a8bd460::icon.index
```

Example 2:  I am not using tooltips, yet.
```
40x ab18b3e58a3b1bb5106ced208a8bd460::button-or-linkbutton-or-link.blade.php#?blade
40x ab18b3e58a3b1bb5106ced208a8bd460::with-tooltip
```

Example 3:  Another icon instances, slightly different from Example 1.
```
10x ab18b3e58a3b1bb5106ced208a8bd460::button.indexindex.blade.php#?blade
10x ab18b3e58a3b1bb5106ced208a8bd460::icon.indexindex.blade.php#?blade
10x __components::13d90c1c0de02b9d64527d38b2e9050913d90c1c0de02b9d64527d38b2e90509.blade.php#?blade
10x ab18b3e58a3b1bb5106ced208a8bd460::icon.x-markx-mark.blade.php#?blade
```

**Comment by JackWH** [comment]
I think this is pretty standard for something like this, and not anything to worry about.

In your second example, the `with-tooltip` view is being called because it wraps around Flux's `button` component, so we can show tooltips on buttons. But if no tooltip value is passed in as a prop, `with-tooltip` simply acts as a container for whatever it's wrapped around.

If you use `php artisan view:cache` when you deploy, the performance overhead of rendering most of these views will be effectively zero. They'll be precompiled once and stored in memory. Good to keep a close eye on models/queries though!

**Comment by lcallif** [comment]
Thank you Jack!  Closing this now.
