### ISSUE TITLE
Select & null

### ISSUE THREAD

**Issue by ju5t** [livewire/flux#413]
Select components don't like `null` as a value. I remember this being an issue in Livewire before. 

We're coming from Alpine components, and we could have a `null` option there without any issues. Perhaps it's something that can be handled in Flux too, especially in the `listbox` variant.

Code:

```blade
@php
$options = [
    null => 'Null',
    'string' => 'String',
];
@endphp

<flux:select variant="listbox" wire:model="selected">
    @foreach($options as $value => $option)
        <flux:option :value="$value">{{ $option }}</flux:option>
    @endforeach
</flux:select>
```

If the `selected` property is set to null nothing gets selected in the listbox. It will show the placeholder if its configured, if not its just an empty box.

**Comment by jeffchown** [comment]
@ju5t With null causing issues when used as an option value, wouldn't it be easier to switch to a string key equivalent, e.g. 'null'?

Making your code:

```
@php
$options = [
    'null' => 'Null',
    'string' => 'String',
];
@endphp

<flux:select variant="listbox" wire:model="selected">
    @foreach($options as $value => $option)
        <flux:option :value="$value">{{ $option }}</flux:option>
    @endforeach
</flux:select>
```

**Comment by ju5t** [comment]
@jeffchown it would, and we've used that in the past. However, in most cases, we prefer the database entry to be `null` too if that option gets selected. It's also difficult if the other values are integers instead of strings -- as you can't always use zero to replace null with.

Perhaps it's more fitting to open this in the Livewire repo. But as it worked for us with the paid Alpine listbox, I'm hoping it's something that's easily solved in Flux too.

**Comment by jeffchown** [comment]
I see, @ju5t .  Tricky use-case.  I wonder if there's a solution that doesn't collide with null = placeholder.

**Comment by LasseRafn** [comment]
totally understand the issue, but I also find it very tricky. On one hand, PHP doesn't have "undefined", its not a thing, besides not setting the variable at all, so null makes sense as the placeholder.. On the other hand I also have had similar workflows before.

Maybe it's worth considering if your UI even needs a select.. what is NULL? Why can you select NULL as an option? Would it perhaps be more suited as a checkbox, or a radio box with a "none" (null) option?

**Comment by ju5t** [comment]
@jeffchown never thought about the placeholder, that's definitely an issue.

@LasseRafn we have no choice but to use a select. There can be any number of values. In most cases these values are all integers, we use null as a 'default' option. This is an option a user can select. We could use `99999999` but there's a chance this value will be used by one of the options. It's not likely, but still possible.

That's why we settled on null, also because it worked with Alpine's listbox. But Flux is better looking and more performant, so I don't want to move back to the previous solution.

The struggles of a developer...

**Comment by calebporzio** [comment]
Hey @ju5t - I see. Yeah I'm trying to make the custom selects (and other custom inputs) mirror the browser native inputs behavior as much as possible so things are consistent and unsurprising. Native selects don't support a null value, they set it to empty string. All native inputs only support string values to my knowledge.

Therefore, I recommend that you handle the null value in the database with some sort of casting of a string back to null and vice versa.

As for the Alpine components thing. Yeah, those components aimed to mirror headless UI's behavior which is more javascripty and less native oriented because it's for JS tools. So although I see the allure there, I think Flux components should be less opinionated and more just like native ones.

Hope that makes sense. Thanks for the report - good discussion.

**Comment by ju5t** [comment]
@calebporzio thanks for the explanation!
