### ISSUE TITLE
flux:checkbox.group is modeling input (search) text also

### ISSUE THREAD

**Issue by DoneItInnovations** [livewire/flux#414]
I use flux:checkbox.group wraping my whole table where the first col is for row checkboxes.
I also have a seach input box at the top, inside the wrap. And if I do searching, the checkbox.group's wire:model element gets the searchbox's values. Thats sad, because i cannot use bulk actions and search together with flux.

**Comment by calebporzio** [comment]
Thank you for the report. Yes, that is because input events bubble up the DOM tree and `wire:model` listens for input events. Therefore you're getting collisions.

Instead you should us `wire:model.self` on the checkbox.group.

However, I need to come up with a better way for using checkbox groups for something like a table without wrapping the entire table in the group. Good report. thanks.
