### ISSUE TITLE
Flux header and sidebar component demo code missing `@fluxScripts` before `</body>`

### ISSUE THREAD

**Issue by jeffchown** [livewire/flux#489]
If people are copying the header and/or sidebar components' demo code and testing it verbatim in a layout blade file, there is no `@fluxScripts` before the `</body>` in the related demo code as indicated in the Installation instructions.

Might be a good idea to add the `@fluxScripts` in the code for those demos to avoid any confusion and possible GitHub issues (for example, maybe, issue https://github.com/livewire/flux/issues/483)

**Comment by dean-stratman** [comment]
To tack onto this issue, I would suggest on the installation section making it clear where the Livewire scripts belong in the layout file. I know, even as a past user of Livewire, I was curious as to whether the @fluxStyles and @fluxScripts needed to be in a specific order for those who manually include Livewire's frontend assets, or if they somehow replaced those (@livewireStyles and @livewireScripts).

Maybe I am dumb, and no one else had this issue/thought, but it probably wouldn't hurt to have a sidenote on that.

**Comment by boettges** [comment]
Oddly enough, as soon as I add `@fluxScripts` accordingly before `</body>` toggling the sidebar will no longer work. It only works _without_ it for me. 🤔

This applies to all the example layouts with a sidebare, provided in the docs.

**Comment by jeffchown** [comment]
@boettges To @dean-stratman 's point, are you adding `@fluxScripts` to your layout file?  My initial post was aimed at when people cut & copy the sidebar demo code directly into a layout file, otherwise it does not apply.

**Comment by calebporzio** [comment]
This is a good suggestion @jeffchown. I wonder two things however if we add this:
* Will people not have @fluxStyles because they think it's taken care of for them?
* Will people errantly have two `@fluxScripts` because they followed the installation instructions already.

---

Ok, so maybe we just add `<head>` as well to the code example to make it crystal clear.

If people start experiencing issues or friction because of this, please re-submit issue

![Image](https://github.com/user-attachments/assets/30570ee4-831d-42f9-b18a-ba763acfce67)

**Comment by jeffchown** [comment]
@calebporzio That sounds like a good idea (re: adding `<head>`)
