### ISSUE TITLE
flux button icon variant 

### ISSUE THREAD

**Issue by eckelarsson** [livewire/flux#499]
Hi,

**Flux button with icon variant**
I notice when I source dived that thier is an icon variant on the flux button, I tried to change it to outline but then the icon sizes and placement just went a little bonkers.

![Image](https://github.com/user-attachments/assets/f800e6d6-9ba0-4fa1-8330-ede7e99cbdaa)

**Comment by calebporzio** [comment]
In general, the reason is, is that each heroicon variant was designed to be used at it's designed size. Otherwise, the strokes in the outline variant get too thin. Also you can into sub-pixel aliasing issues as well, making them not look as crisp:

![Image](https://github.com/user-attachments/assets/60a5037e-acc8-4b5f-8daa-9690eadd5eee)

You can always include the icon in the slot by hand if you need downsized outline icons.

I'm going to keep this in mind as a feature request instead of an issue for now. thanks
