### ISSUE TITLE
Google Captcha in a modal

### ISSUE THREAD

**Issue by JeromeSiau** [livewire/flux#542]
Hi there! 👋

I have an issue using the modal component. 
I'm using it with a form and a captcha (V2) at the end.

My issue is, if google decide to challenge us with the captcha, the captcha window open ... under the modal.

![Image](https://github.com/user-attachments/assets/5ac40921-fad2-4a34-b0e9-dd88af69da33)

Any idea how I could fix this?

Thx!
Jerome

**Comment by nicolaslefresne** [comment]
I think I saw a similar issue with other libraries and everything pointed out to the <dialog> behaviour just not implementing the possibility to tweak z-index...

**Comment by roadsend** [comment]
I found capture worked okay in a modal from cloudflare, but only once if
you had multiple on the same page they would not load. It's an issue with
cloudflare not flux

**Comment by calebporzio** [comment]
Yeah, I think the same problem exists with google maps autocomplete because they are using their own modal strategy that conflicts with the native browser dialog element.

For now, Flux is going to continue to use the dialog element as it offers some distinct advantages over custom ones, hopefully Google addresses this.
