### ISSUE TITLE
Multiple selects are not supported in this version of Flux...

### ISSUE THREAD

**Issue by David-Grass-Feria** [livewire/flux#564]
Hello Caleb.
I buyed your flux pro, because i saw your multiple select on laracon. 
And now they are not supported? I installed the lastest version.
Many thanks

**Comment by 3adeling** [comment]
https://github.com/livewire/flux/discussions/513#discussioncomment-11024866

**Comment by calebporzio** [comment]
Working on it as we speak - I removed it because after talking with folks the multiple selects as-is aren't what some people wanted and I didn't want to release something I almost immediately regretted. Coming soon though - it's next on my priority list.

Please email support@fluxui.dev if you don't want to use Flux and want a refund - no problem.
