### ISSUE TITLE
Unable to change text color in the component flux:text

### ISSUE THREAD

**Issue by Ashraam** [livewire/flux#567]
Hey fluxers,

We can't overwrite the color of the text while using the component `flux:text`

```php
<flux:text class="text-green-500">my green text</flux:text>
```

render:
![Image](https://github.com/user-attachments/assets/f3a0990e-dab5-475f-b5c4-06cbd94069dc)

**Comment by jeffchown** [comment]
From the fluxui.dev docs:

For example, you may try to customize the background color of a button by passing in the bg-zinc-800 Tailwind utility class:
 
<flux:button class="bg-zinc-800 hover:bg-zinc-700">

However, because flux applies it's own bg-* attributes, both classes will be rendered in the output HTML:
 
<button type="button" class="bg-zinc-800 hover:bg-zinc-700 bg-white hover:bg-zinc-100...">

Because both classes exist on the element, the one defined last in CSS wins.

Tailwind's important (!) modifier is the simplest way to resolve these conflicts:

<flux:button class="!bg-zinc-800 hover:!bg-zinc-700">

**Comment by Ashraam** [comment]
Thanks Jeff, yes it works when using the important modifier (!).

**Comment by jeffchown** [comment]
You're welcome @Ashraam
