### ISSUE TITLE
Listbox Select - Alignment Issue with Selected Item

### ISSUE THREAD

**Issue by Cbrad24** [livewire/flux#573]
Flux Version: v1.0.18

When using `<flux:select variant="listbox">` it appears that `<flux:option>` applies flexbox with center item alignment, however `<ui-selected-option>` does not apply the same.

The result is additional elements like icons do not align properly when displayed as a selected item:

![Image](https://github.com/user-attachments/assets/8c6af9ef-6b1b-4619-936b-f5c862265653)

By applying flexbox to `<ui-selected-option>` the alignment sits properly once again:

![Image](https://github.com/user-attachments/assets/5efdd64d-7dc2-40f8-84d6-88a8b4888d29)

![Image](https://github.com/user-attachments/assets/87a39d94-6fea-4e5d-ba17-42013896037e)

Code:
```blade
<flux:select variant="listbox" searchable placeholder="Select channel...">
    <flux:option>
        <flux:icon.hashtag class="me-1" variant="micro" />
        general
    </flux:option>

    <flux:option>
        <flux:icon.lock-closed class="me-1 size-4" />
        sms-messages
    </flux:option>
</flux:select>
```

Thanks in advance.

**Comment by calebporzio** [comment]
The contents of `<flux:option>` will be directly copied into the select button element. Because of this, you are losing any styles added to `<flux:option>`.

We recommend adding a wrapping div to contain your flex styles. 

I added a section in the docs to make this clear for folks: https://fluxui.dev/components/select#options-with-images/icons
