### ISSUE TITLE
In update 1.0.20 default flux:checkboxes en <flux:radio.group wire:model.live="..." are not binding anymore.

### ISSUE THREAD

**Issue by mitsswebdesign** [livewire/flux#601]
Since update 1.0.20 default flux:checkboxes en <flux:radio.group wire:model.live="..." are not binding and update anymore with wire:model(.live); Strange thing: add any variant like variant="segmented" to radio.group and the binding is repaired.

**Comment by ThomasEnssner** [comment]
```html
  <flux:checkbox.group wire:model="receivers" label="Receivers" class="grid grid-cols-4">
    @foreach($this->allowedReceivers as $allowedReceiver)
      <flux:checkbox
          :label="$allowedReceiver->last_name"
          :value="$allowedReceiver->id"
      />
    @endforeach
  </flux:checkbox.group>
```

Doesn't bind to livewire and throw the validation error: "Receivers must be filled"

**Comment by cstisa** [comment]
I confirm, there a problem since 1.0.20

I had this :
![Image](https://github.com/user-attachments/assets/6c0c3b86-9844-4cdf-b219-ca22c13e8369)

Now, without changing anything my code :
![Image](https://github.com/user-attachments/assets/a5577701-22b6-4755-bc9b-9b6bddeae9f7)

I get no error in the console.

**Comment by seabasss** [comment]
Also, and maybe related, `flux:checkbox.all` is not selected as default anymore in `1.0.20`, even if all checkboxes are checked.

**Comment by asp111** [comment]
Stump on a similar issue. I have custom rules set up to display subfields fields based on group radio selection and it was working before 1.0.20 update. Found the issue is when clicking on the radio **_label_**, it does not work however it shows the radio circle as active. Clicking directly on the radio circle works. So some bug in the label and radio circle connection. I tried the  variant="segmented" approach and it works.

**Comment by erikwestlund** [comment]
I have this same issue. Clicking the checkboxes works. Clicking the label does not.

**Comment by ju5t** [comment]
@asp111 and @erikwestlund The issue with the label is also described here #611.

I'm not sure if the other issues are related?

@cstisa have you tried clearing your views with `php artisan view:clear`?

@ThomasEnssner can you share a copy/pasteable example? I've tried the one below and that works:

```php
<?php
\Livewire\Volt\state([
    'notifications' => [],
])
?>

<div class="p-6">
    @json($notifications)
    <flux:checkbox.group wire:model.live="notifications" label="Notifications">
        <flux:checkbox label="Push notifications" value="push" checked />
        <flux:checkbox label="Email" value="email" checked />
        <flux:checkbox label="In-app alerts" value="app" />
        <flux:checkbox label="SMS" value="sms" />
    </flux:checkbox.group>
</div>
```

I'm not able to click the labels but that's described in #611.

**Comment by calebporzio** [comment]
This was caused because of a bug/quirk in the `<x-dynamic-component>` Blade component that we switched to in the latest release for checkboxes and radios. It only happens when you use dynamic components with anonymous components, and only effects certain types of properties so it was kinda hard to pin down.

Anyhow, it's fixed and I will tag a new release as soon as I test it a little more.
