### ISSUE TITLE
```wire:model.live``` on input ```type="password"``` ```"viewable"``` breaks on input change.

### ISSUE THREAD

**Issue by shmdesign** [livewire/flux#606]
Hello,

I am trying to wire up an ```input``` type password with the ```viewable``` attribute like so:

```php
// SignIn class
{
   public string $password = '';

  [...]
}
```

```html
<!-- sign-in.blade.php -->
[...]
<flux:input wire:model.live="password" type="password" viewable />

[...]
```

Now, when I toggle the viewable button everything works fine. If I "open" the state of the input so that the input changes from ```type="password"``` to ```type="text"``` AND I start typing again, a network round trip is fired and the input turns back to ```type="password"``` BUT the toggle icon does not change. Just to be clear, the state of the icon is correct as it does not change whereas the state of the input changes back to ```type="password"``` when it should not.

WORKAROUND:
I managed to make it work but I feel like this is a patch and not a fix. By adding a ```wire:ignore``` to the input, everything works as expected:

```html
<!-- NEW sign-in.blade.php -->
[...]
<flux:input wire:ignore wire:model.live="password" type="password" viewable />

[...]
```

I hope this helps.

Thank you so much for this wonderfull library!

Eliott

**Comment by calebporzio** [comment]
Good report - this actually makes sense. The viewable button changes the type attribute on the input from `password` to `text`, however, this change will get "reset" if there is a Livewire request because the HTML from the server will always be `password`.

I added a mutation observer to ensure that the input type is not able to be tampered with my DOM morphing like Livewire does.

Fix will be in the next release. Thanks.
