### ISSUE TITLE
[1.0.23] Flux::Profile - Special Characters Not Displayed Correctly

### ISSUE THREAD

**Issue by jlcara** [livewire/flux#707]
#### Description
Special characters such as apostrophes and ampersands are not rendered correctly when displaying a variable name in the profile component. Instead, they appear as HTML entities (e.g., `&#039;` for apostrophes and `&amp;` for ampersands).

#### Steps to Reproduce
```blade
@php
    $name = "flux's components"
@endphp

<flux:profile
    avatar="https://fluxui.dev/img/demo/user.png"
    name="{{ $name }}" />
```

#### Expected Behavior
`flux's comp...`

#### Actual Behavior
`flux&#039;s comp...`

![Image](https://github.com/user-attachments/assets/e806eb85-262b-405e-b97f-e86b51ca9f76)

#### Fix editing profile.blade.php

Wrap $name with html_entity_decode

```blade
...

    <?php if ($name): ?>
        <span class="ml-2 text-sm text-zinc-500 dark:text-white/80 group-hover:text-zinc-800 group-hover:dark:text-white font-medium truncate">
            {{ html_entity_decode($name) }}
        </span>
    <?php endif; ?>

...
```

**Comment by calebporzio** [comment]
The fix is to bind the variable directly like so:

```php
<flux:profile
    avatar="https://fluxui.dev/img/demo/user.png"
    :name="$name" />
```

This a double-encoding problem. It actually exists inside any Blade component, not just Flux.

If you have a component like this:

```php
@props([
    'name' => '',
])

<div>{{ $name }}</div>
```

You can see that `$name` is encoded before echoing (because of `{{ }}`)

If you pass a variable using typical prop binding like so:

```
<x-your-component :name="$name" />
```

All is well, `$name` will get passed in directly, then encoded in the component view.

However, if you use the echo syntax like so:

```php
<x-your-component name="{{ $name }}" />
```

The `$name` string will be encoded before it's passed into the component, then encoded again when being echoed in the view.

The first encoding turns `flux's components` into `flux&#039;s components`
The second one turns `flux&#039;s components` into `flux&amp;#039;s components`

Then the `flux&amp;#039;s components` string will get processed by the browser (turning `&amp;` back into an ampersand) and render as: `flux&#039;s components`

Therefore, the only real solution I can recommend at this point is to use the typical binding syntax instead of the echo syntax.

Thanks for the report. Hope this helps.

**Comment by igmltd** [comment]
> The fix is to bind the variable directly like so:
> 
> <flux:profile
>     avatar="https://fluxui.dev/img/demo/user.png"
>     :name="$name" />
> This a double-encoding problem. It actually exists inside any Blade component, not just Flux.
> 
> If you have a component like this:
> 
> @props([
>     'name' => '',
> ])
> 
> <div>{{ $name }}</div>
> You can see that `$name` is encoded before echoing (because of `{{ }}`)
> 
> If you pass a variable using typical prop binding like so:
> 
> ```
> <x-your-component :name="$name" />
> ```
> 
> All is well, `$name` will get passed in directly, then encoded in the component view.
> 
> However, if you use the echo syntax like so:
> 
> <x-your-component name="{{ $name }}" />
> The `$name` string will be encoded before it's passed into the component, then encoded again when being echoed in the view.
> 
> The first encoding turns `flux's components` into `flux&#039;s components` The second one turns `flux&#039;s components` into `flux&amp;#039;s components`
> 
> Then the `flux&amp;#039;s components` string will get processed by the browser (turning `&amp;` back into an ampersand) and render as: `flux&#039;s components`
> 
> Therefore, the only real solution I can recommend at this point is to use the typical binding syntax instead of the echo syntax.
> 
> Thanks for the report. Hope this helps.


Thanks for this for this brilliant explanation, so useful to know in general.
