### ISSUE TITLE
Clear icon overlaps select icon in clearable combobox

### ISSUE THREAD

**Issue by MiguelLaforest** [livewire/flux#715]
![Image](https://github.com/user-attachments/assets/36d0cddd-5787-4a3d-99a0-6bf2ca62233c)

```blade
@php
    $available_clients = [];
@endphp

<flux:field>
    <flux:label>{{ __('Client search') }}</flux:label>
    
    <flux:input.group>
        <flux:select
            variant="combobox"
            wire:model="selected_client"
            icon="magnifying-glass"
            :filter="false"
            clearable
        >
            <x-slot name="input">
                <flux:select.input
                    wire:model.live.debounce.500ms="client_search"
                    icon="magnifying-glass"
                    clearable
                />
            </x-slot>
            
            @foreach ($available_clients as $id => $name)
                <flux:option wire:key="clients-search-{{ $id }}" :value="$id">
                    {{ $id }} - {{ $name }}
                </flux:option>
            @endforeach
        </flux:select>
        
        <flux:button
            wire:click="addClient"
            icon="plus"
        />
    </flux:input.group>
</flux:field>
```

**Comment by calebporzio** [comment]
Currently, we do not support "clearable" on combobox inputs. Users can use "backspace" (the text is auto-selected when focused) or "Escape" to clear the input.

The reason is that the additional styling required is complex given that the buttons are absolutely positioned and variable padding would need to be added to the input element itself.

For those reasons we're going to continue to not support this, however, if you disagree with this decision or others are visiting this issue and think it's too important of a feature to neglect, please open a new issue.

Thank you.
