### ISSUE TITLE
Tailwind 4 compatible?

### ISSUE THREAD

**Issue by vincentcordel** [livewire/flux#754]
I'm wondering if using Tailwind 4 will break Flux with compatibility issues?

Not a bug I know but not a feature request either :)

**Comment by ju5t** [comment]
It's a bit early, they just released the first beta release of Tailwind v4.

**Comment by calebporzio** [comment]
We should be good.

Adam said this lol:
![Image](https://github.com/user-attachments/assets/edd53a10-0d19-4215-93b5-5b3054a1bbb6)

Flux doesn't actually include anything specificly intertwined with the tailwind config process which makes this particularly easy for us to support TW4, pretty much a matter of making sure our utilities are still supported.

After looking at the beta notes, the only things I think we'll have to be aware of are:
* `shadow` will become `shadow-sm` and `shadow-sm` will become `shadow-xs`
* Same with rounded scale change (although this will be better because most of our roundeds are above "sm")

---

Going to close this. We will add TW4 support when it comes out.

**Comment by timkley** [comment]
@calebporzio 

I've wanted to let you know that there is one issue I've found when using TailwindCSS v4 that stems from the way Flux injects CSS and the upcoming support of native CSS layers.

### Problem

This is a what a segmented radio group looks like:

![Image](https://github.com/user-attachments/assets/5274ace1-56e3-4d21-a38d-c64f8d83e531)

And this is the generated CSS:

![Image](https://github.com/user-attachments/assets/397a229e-626c-4839-b19d-8f97475d596e)

Since`.flex` is now in the layer `utilities` the injected styles will take precedence since they have no layer definition.

### Solution

A quick fix would be to wrap all styles in a `components` layer, e.g. like this:

`utils.js#6`
```js
let styles = ....

styles = `@layer components { ${styles} }`;

```

Hope this helps in supporting TW4 early on :)

**Comment by joshhanley** [comment]
@timkley thanks for that! Can you open a new issue for that particular problem and include all the details there? Thanks!
