### ISSUE TITLE
Select field placeholder doesn't dynamically change, but label will?

### ISSUE THREAD

**Issue by robMarcoPolo** [livewire/flux#765]
Not sure if this is a Flux issue, Livewire issue, or a 'me' issue - I'm relatively new to Laravel, Livewire and Flux!  

I have a select which has a label and placeholder - both of which are dynamic based on the underlying class - i.e. the `$state_terminology` variable:

```Blade
<flux:field>
  <flux:label>{{$state_terminology}}</flux:label>
  <flux:select variant="listbox" wire:model="state_id" placeholder="Select {{$state_terminology}}..." searchable="">
     @foreach($states as $state)
        <flux:option wire:key="{{$state->id}}" value="{{$state->id}}">{{$state->name}}</flux:option>
     @endforeach
  </flux:select>
  <flux:error name="state_id" />
</flux:field>
```

When the corresponding country select changes, the component calls a function within the class which pulls the relevant terminology used in the country to describe it's states/counties/districts/principalities.

While the label changes dymanically when the underlying variable in the class changes, the placeholder doesn't seem to?  It would make more sense to me if both did (or didn't), but the fact one does and the other doesn't makes me think it might be a Flux issue?

Any help appreciated.

**Comment by lotje-kinable** [comment]
@robMarcoPolo did you try wire:model.change="state_id" or wire:model.live="state_id ? Because (that's how I see it) the flux:select will get the correct state because you selected it from the flux:option, but without change or live, Livewire does not know that state_id changed, so it won't update and so the $state_terminology stays the same. 

When you are using a form, and nothing needs to happen when you select a value/ add input/ ... , wire:model is perfect (less updates to server) but in this case you want it to change. 

(Feel free to correct me if I am wrong! )

**Comment by ju5t** [comment]
My first thought is that it could be a dom-diffing thing in Livewire. Could you try adding a `wire:key="{{ $state_terminology }}"` to the `flux:field`? I'm hoping this will completely refresh the dropdown when you change the variable.

**Comment by jeffchown** [comment]
@robMarcoPolo Can you provide a full code sample that reproduces the issue? (a Volt component is great for this)

**Comment by jeffchown** [comment]
What @ju5t suggest should work as it will essentially make the `state_id` `flux:select` reactive to any change in the country select's value (and the resulting change to the `state_terminology`)

**Comment by robMarcoPolo** [comment]
Thank you!  That seems to have done the trick!

**Comment by clarkewing** [comment]
This helped me too, thanks!
