### ISSUE TITLE
Submitting checkbox group prepends an empty value to an array

### ISSUE THREAD

**Issue by iapparatus** [livewire/flux#812]
Flux 1.0.25+ (The code works fine on 1.0.24 but has an issue on 1.0.28)

I have a json object that I load into the form for editing:
```
{
  "01jdn7j5f56nghrxf3kz4abjzd": ["1", "2", "3", "4", "5"]
}
```

mount method:
```
$this->formData = Application::where('applicant_id', $this->applicant->id)
    ->first()
    ->application_data ?? json_encode($this->formData);
$this->formData = json_decode($this->formData, true);
```

form element:
```
<flux:checkbox.group wire:model.defer="formData.{{ $field->ulid }}" label="{{ $field->title }}">
      @foreach (json_decode($field->options, true) as $value => $option)
          <flux:checkbox label="{{ $option['label'] }}" value="{{ $value }}" />
      @endforeach
 </flux:checkbox.group>
```

submission result with an empty element:
```
array:5 [▼ // app/Livewire/Forms/ApplicationForm.php:102
  "01jdn7j5f56nghrxf3kz4abjzd" => array:5 [▼
    0 => ""
    1 => "1"
    2 => "2"
    3 => "3"
    4 => "4"
    5 => "5"
  ]
]
```

**Comment by ju5t** [comment]
Could you share some code that we can copy/paste to test what you're seeing? Volt-components are great for that.

**Comment by joshhanley** [comment]
@iapparatus Thank you for the report, however we have been unable to reproduce this given the information available. Please submit a code snippet we can copy and paste into our own apps with steps to reproduce. Be sure to include any Blade variable definitions that are used and use a little code as possible to reproduce the issue. Then, we will be happy to help.

**Comment by jeffchown** [comment]
@iapparatus I think I remember a similar posted issue a while back, are you making sure you initialize each `formData.{{ $field->ulid }}` as an array? (even an empty array `[]` if no json data)

If that's not the issue, then, per @joshhanley and @ju5t , please submit a full code snippet.

**Comment by iapparatus** [comment]
I will work on creating a better code snippet, but I have many fields stored in `formData`, and not all of them are supposed to be arrays.

**Comment by jeffchown** [comment]
@iapparatus I'm only referring to the ones `wire:model`ed into your `flux:checkbox.group`s

PS I'd add a `wire:key` to each `flux:checkbox`

**Comment by iapparatus** [comment]
Adding `wire:key` to each `flux:checkbox` didn't solve the problem, but I was able to initialize each appropriate field in my `formData` as an empty array through a `foreach` loop in the component's render method.

Thank you for your help. I will close the issue.

**Comment by jeffchown** [comment]
You're welcome, @iapparatus

**Comment by joshhanley** [comment]
Turns out there was a bug with how the checkbox group was initialised. I've submitted a PR with a fix.

# The scenario

Currently if you `wire:model` a checkbox group to an empty property and then select a checkbox, the resulting array has an addition empty string item prepended to it.

<img width="203" alt="image" src="https://github.com/user-attachments/assets/20cd9655-0efb-4522-888a-9cda2e731f3d" />

```blade
<?php

use Livewire\Volt\Component;

new class extends Component {
    public $notifications;
};
?>

<div>
    @json($notifications)   

    <flux:checkbox.group wire:model.live="notifications" label="Notifications">
        <flux:checkbox label="Push notifications" value="push" />
        <flux:checkbox label="Email" value="email" />
        <flux:checkbox label="In-app alerts" value="app" />
        <flux:checkbox label="SMS" value="sms" />
    </flux:checkbox.group>
</div>
```

# The problem

The problem is that it is never being initialised to an empty array like it should be. Instead internally it's state is being initialised to an empty string. So then when a new item is added, we check to see if it currently is an array, and if not call `Array.from(this.state)` which is then creating an array where the first item is an empty string.

```js
getState() {
    return this.options().multiple ? Array.from(this.state) : this.state
}
```

# The solution

The reason it was never being initialised to an empty array is because there was a check for `this.multiple` instead of `this.options().multiple` in `SelectableGroup` in `selectable.js`.

```js
if (value === null) value = this.options().multiple ? [] : ''
```

So the PR fixes that.
