### ISSUE TITLE
[Documentation] flux:table code example

### ISSUE THREAD

**Issue by dicktornfeldt** [livewire/flux#84]
URL: https://fluxui.dev/components/table

In the code example for the first table `$orders` should be `$this->orders` as the orders are a computed property in the Livewire component example code.

`<flux:table :paginate="$orders">` --> `<flux:table :paginate="$this->orders">`
and
`@foreach ($orders as $order)` --> `@foreach ($this->orders as $order)`

**Comment by lcallif** [comment]
The current Livewire Blades do not require the "this->" in order to work properly.  Please refer to LaravelDaily's Livewire YouTube classes as an example.  

As an example:

Livewire Component
--------------------
$this->boms = Bom::where('bom_id',$this->theID)
            ->orderby('typeId')
            ->get();

And in the Livewire blade:
   @foreach ($bomcomponents as $bomcomponent)
             ........
             ........
   @endforeach

Have a good day.

**Comment by ahosker** [comment]
> The current Livewire Blades do not require the "this->" in order to work properly. Please refer to LaravelDaily's Livewire YouTube classes as an example.

Interesting, $this-> is required for me. Perhaps its because I'm rendering the HTML inside the livewire component instead of a blade file.

**Comment by idealerror** [comment]
Per the [Livewire Computed Properties docs](https://livewire.laravel.com/docs/computed-properties), it's recommended to use `$this->` in your blade components.

Specifically this notice:
> **Must use `$this` in your template**
Unlike normal properties, computed properties aren't directly available inside your component's template. Instead, you must access them on the $this object. For example, a computed property named posts() must be accessed via $this->posts inside your template.
